(:primitives (:number ((x ())
                       (y ())
                       (#(-5 5) ())
                       (+ (:number :number))
                       (- (:number :number))
                       (* (:number :number))
                       (/ (:number :number))
                       (sqrt (:number))
                       (if (:bool :number :number)))
              :bool ((or (:bool :bool))
                     (and (:bool :bool))
                     (= (:number :number))
                     (/= (:number :number))
                     (>= (:number :number))
                     (> (:number :number))
                     (<= (:number :number))
                     (< (:number :number))))
                     ;(t ())
                     ;(NIL ())))
 :parameters (('x 'y) (:number))
 :answer (sqrt (+ (* x x) (* y y))))
