(defun main ()
  (setq *random-state* (make-random-state t))
  (let* ((opts (parse-args))
         (conf (read-config (getf opts :filename)))
         (population (make-array (getf opts :initial-pop)))
         (mutated (make-array (getf opts :initial-pop))))
    (dotimes (i (getf opts :initial-pop))
      (setf (elt population i) (build-tree (getf opts :initial-depth)
                                           (getf conf :primitives)
                                           (caadr (getf conf :parameters)))))
    (dotimes (i (length population))
      (setf (elt mutated i) (mutate (elt population i)
                                    (getf opts :mutation-depth)
                                    (getf conf :primitives))))
    (dotimes (i (getf opts :initial-pop))
      (format t "~%~a: ~a~%" i (elt population i))
      (format t "===~%~a~%~%" (elt mutated i)))))

(main)
