env = Environment(tools=['default', 'clisp'])
def addlisp(s): return s + ".lisp"
def addlib(s):  return s + ".lib"

# Note: file with main routine must come last among sources
ev_sources = ["safety",
              "crossover",
              "fitness",
              "generation",
              "biasing",
              "mutate",
              "tree",
              "load",
              "evolve"]

run_sources = ["safety",
               "run"]

evolve = env.ClispProgram("evolve", map(addlisp, ev_sources))
env.Clean(evolve, map(addlib, ev_sources))

run = env.ClispProgram("run_ev", map(addlisp, run_sources))
env.Clean(run, map(addlib, run_sources))

env.Install('/usr/local/bin', [evolve, run])
env.Alias('install', '/usr/local/bin')

# vim: ft=python
